tap "caryll/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "universal-ctags/universal-ctags"
brew "autoconf"
brew "automake"
brew "bat"
brew "cmake"
brew "coreutils"
brew "exercism"
brew "openssl"
brew "readline"
brew "sqlite"
brew "python@2"
brew "libpq"
brew "python"
brew "gdal"
brew "git"
brew "gnupg"
brew "htop"
brew "hub"
brew "libtool"
brew "imagemagick@6", link: true
brew "libidn"
brew "libmikmod"
brew "libyaml"
brew "mit-scheme"
brew "neovim"
brew "openssl@1.1"
brew "pinentry-mac"
brew "pkg-config"
brew "portmidi"
brew "postgresql@9.4", restart_service: true, link: true
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ruby-build"
brew "sdl"
brew "sdl_image"
brew "sdl_mixer"
brew "sdl_ttf"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "ttfautohint"
brew "vim", args: ["with-override-system-vi"]
brew "watchman"
brew "wget"
brew "zplug"
brew "zsh"
brew "caryll/tap/otfcc-mac64"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "react-native-debugger"
